apiVersion: v1
kind: Service
metadata:
  name: gfj-frontend
  namespace: gfj-app
spec:
  type: ClusterIP
  selector:
    app: gfj-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
