---
apiVersion: v1
kind: Service
metadata:
  name: gfj-frontend
  namespace: gfj-frontend
spec:
  selector:
    app: gfj-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30096
  type: NodePort