replicaCount: 2

image:
  tag: git-01a129e   # stable tag .controlled promotion later

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Gi

ingress:
  enabled: true
  host: gfj-prod.company.com
  tls:
    enabled: true
    secretName: gfj-dev-tls